<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0028)http://staging.agora.gov.gr/ -->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
        <meta name="language" content="en">
            
                <!-- blueprint CSS framework -->
                    <link rel="stylesheet" type="text/css" href="./css/screen.css" media="screen, projection">
                        <link rel="stylesheet" type="text/css" href="./css/print.css" media="print">
                            <!--[if lt IE 8]>
                                <link rel="stylesheet" type="text/css" href="/css/ie.css" media="screen, projection" />
                                    <![endif]-->

                                        <link rel="stylesheet" type="text/css" href="./css/main.css">
                                            <link rel="stylesheet" type="text/css" href="./css/form.css">
                                                <link rel="stylesheet" type="text/css" href="./css/template.css">
                                                    
                                                        
                                                            <title>Μητρώο Αιτημάτων, Προκηρύξεων, Συμβάσεων &amp; Εντολών Πληρωμής</title>
                                                            <style type="css">

                                                            th.ui-datepicker-week-end,
                                                            td.ui-datepicker-week-end {
                                                                display: none;
                                                                }
                                                                </style>
                                                                </head>

                                                                <body>
                                                                <div id="feedback" style="margin:0;padding:0;">
                                                                    <a href="javascript: openwindow()"><span class="css-vertical-text">Πείτε μας τη Γνώμη σας!! </span></a>
                                                                    </div>
                                                                    <div class="ext-wrapper"><!-- ends at footer.php -->
                                                                        <div class="top"></div>
                                                                            <div class="main">
                                                                                    <div class="content-container">
                                                                                                <div class="content">

                                                                                                                <div style="margin-left:60px;">
                                                                                                                                    <img src="./images/logoGR.png" style="margin-left:40px;" alt="Υπουργείο Ανάπτυξης, Ανταγωνιστικότητας και Ναυτιλίας" title="Υπουργείο Ανάπτυξης, Ανταγωνιστικότητας και Ναυτιλίας">
                                                                                                                                                        <br><a href="http://www.mindev.gov.gr/" target="_blank">Υπουργείο Ανάπτυξης,<br>  Ανταγωνιστικότητας και Ναυτιλίας</a>
                                                                                                                                                                        </div>
                                                                                                                                                                                        <div class="clear"></div>
                                                                                                                                                                                                        
                                                                                                                                                                                                                        <div class="header">
                                                                                                                                                                                                                                            <div class="logo"><a href="http://staging.agora.gov.gr/index.html">Αγορά</a></div>
                                                                                                                                                                                                                                                                    <br>
                                                                                                                                                                                                                                                                                            <div style="color: #555;font-size: 12px;margin-top: -12px;padding-left: 680px;font-style:italic;font-weight:bold">                      
                                                                                                                                                                                                                                                                                                                    Ηλεκτρονικό Μητρώο Δημοσίων <br>Συμβάσεων<br>Σε πιλοτική Λειτουργία                       </div>
                                                                                                                                                                                                                                                                                                                                            <div class="clear"></div>
                                                                                                                                                                                                                                                                                                                                                                <br>
                                                                                                                                                                                                                                                                                                                                                                                                    </div><!--  header end -->
                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="clear"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div id="mainmenu">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ul id="yw2">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ul>               </div><!-- mainmenu -->

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <!-- breadcrumbs -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="TryMain">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="span-19">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div id="content">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style="padding-left:20px;width:700px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div id="content">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h1>Διαδικασία Συντήρησης</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ΤΟ ΜΗΤΡΩΟ ΑΙΤΗΜΑΤΩΝ ΠΡΟΜΗΘΕΙΩΝ - ΣΥΜΒΑΣΕΩΝ ΒΡΙΣΚΕΤΑΙ ΠΡΟΣΩΡΙΝΑ ΕΚΤΟΣ ΛΕΙΤΟΥΡΓΙΑΣ ΛΟΓΩ ΣΥΝΤΗΡΗΣΗΣ.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div><!-- content end-->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div><!-- wrapper end-->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="clear"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <!-- footer -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="bottom">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="footer">Σχεδιάστηκε από την <a href="http://www.opengov.gr/" target="_blank">Ομάδα Ηλεκτρονικής Διακυβέρνησης του Γραφείου του Πρωθυπουργού</a> σε συνεργασία με την Γενική Γραμματεία Εμπορίου.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Yλοποιήθηκε με χρήση <a href="http://mathe.ellak.gr/" target="_blank">ΕΛ/ΛΑΚ λογισμικού</a>. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="http://validator.w3.org/check?uri=referer" target="_blank">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img src="./images/valid-xhtml10.png" alt="Valid XHTML 1.0 Transitional" height="21" width="56"></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="http://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fstaging.agora.gov.gr%2Fcss%2Fscreen.css&profile=css21&usermedium=all&warning=1&vextwarning=" target="blank">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img style="border:0;width:56px;height:21px" src="./images/vcss.gif" alt="Valid CSS!">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div><!-- footer -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="footer-copyright"><img src="./images/cc.png" alt="CC Copyright" title="CC Copyright"> &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;<span style="padding-left:160px;width:340px;">&nbsp;</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div><!-- footer-copyright -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <!-- footer end-->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <script type="text/javascript">   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function openwindow() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      window.open("http://ticketing.ktpae.gr/agora/Default.aspx?frm=4",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "mywindow","location=0,status=0,scrollbars=1,width=820,height=1200");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } </script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div><!-- ext-wrapper ends -->


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </body></html>
