<?php
var	x=document.getElementById('Contractitempayments_'+number+'_quantity').value;
    	document.getElementById('Contractitempayments_n'+lastStudent+'_quantity').value=x;
    var	y=document.getElementById('Contractitempayments_'+number+'_units_of_measure').value;
     	document.getElementById('Contractitempayments_n'+lastStudent+'_units_of_measure').value=y;
    var	x=document.getElementById('Contractitempayments_'+number+'_cost').value;
      	document.getElementById('Contractitempayments_n'+lastStudent+'_cost').value=x;
    var	x=document.getElementById('Contractitempayments_'+number+'_vatid').value;
      	document.getElementById('Contractitempayments_n'+lastStudent+'_vatid').value=x;    
    var	x=document.getElementById('Contractitempayments_'+number+'_currencyid').value;
      	document.getElementById('Contractitempayments_n'+lastStudent+'_currencyid').value=x;      
    var y=document.getElementById('Contractitempayments_'+number+'_address').value;
     	document.getElementById('Contractitempayments_n'+lastStudent+'_address').value=y;
    var y=document.getElementById('Contractitempayments_'+number+'_addressNo').value;
      	document.getElementById('Contractitempayments_n'+lastStudent+'_addressNo').value=y;
	var y=document.getElementById('Contractitempayments_'+number+'_addressPostal').value;
       	document.getElementById('Contractitempayments_n'+lastStudent+'_addressPostal').value=y;
   	var y=document.getElementById('Contractitempayments_'+number+'_city').value;
    	document.getElementById('Contractitempayments_n'+lastStudent+'_city').value=y;
	var y=document.getElementById('Contractitempayments_'+number+'_countryOfDelivery').value;
    	document.getElementById('Contractitempayments_n'+lastStudent+'_countryOfDelivery').value=y;
    var y=document.getElementById('Contractitempayments_'+number+'_countryProduced').value;
    	document.getElementById('Contractitempayments_n'+lastStudent+'_countryProduced').value=y; 
    var y=document.getElementById('Contractitempayments_'+number+'_responsibilityAssumptionCode').value;
		document.getElementById('Contractitempayments_n'+lastStudent+'_responsibilityAssumptionCode').value=y; 
   var y=document.getElementById('Contractitempayments_'+number+'_description').value;
   		document.getElementById('Contractitempayments_n'+lastStudent+'_description').value=y; 
   		document.getElementById('Contractitempayments_n'+lastStudent+'_description').title=y; 

   		//	theInput =document.getElementById('textearea.Contractitempayments_n'+lastStudent+'_description');
//	alert(y);
//		var el = document.createElement("input"); 
	//	 el.type = "hidden";
	//	 el.name = 'Contractitempayments_n'+lastStudent+'_description';
   	 //   el.value = y;
   	  // theInput.appendChild(el);
   var y=document.getElementById('Contractitempayments_'+number+'_cpvsid').value;
  		document.getElementById('Contractitempayments_n'+lastStudent+'_cpvsid').value=y; 
   var y=document.getElementById('Contractitempayments_'+number+'_notice').value;
   		document.getElementById('Contractitempayments_n'+lastStudent+'_notice').value=y; 
   var y=document.getElementById('Contractitempayments_'+number+'_documentUrl').value;
   		document.getElementById('Contractitempayments_n'+lastStudent+'_documentUrl').value=y; 
